### ISSUE TITLE
Format of raw data 

### ISSUE THREAD

**Issue by kruse-alex** [mluders/tweetwise#1]
Hi! I downloaded your data from the google drive but I can't figure out how to import it (into R). Are there any seperators or how does that work? :)

**Comment by kruse-alex** [comment]
Just to make this clear, I am working with data for years and have imported tons of datasets into R :)

**Comment by mluders** [comment]
I uploaded a new file titled 'prices_formatted.txt' which should be more R-friendly.

Each line is comprised of a single tweet, comprised of the following information:
`tweet author || tweet body || date`

The information is delimited by "||".

Hope that helps!

**Comment by kruse-alex** [comment]
It was more about the tweets. If I open the file with a text editor I can't see any delimiters? No double pipes. Maybe you have the chance to format it as classic csv?

**Comment by mluders** [comment]
Oh I apologize, my last message was incorrect. The file is called ""tweets_formatted.txt." That should have the formatted tweets with delimiters.

Also, I can create a .csv version and upload it tonight, if that would be helpful 😀

**Comment by Metaphor31** [comment]
Hi Miles, Thanks for your work, I am starting to look at the same ideas from the paper. 
Could you please explain how to read your text file or share tutorials/help on functions you used to read them ? 
to use this : 
def get_svm_features(tweets, featureList):
    sortedFeatures = sorted(featureList)
    map = {}
    # print tweets
    feature_vector = []
    labels = []
    for t in tweets:
        label = 0
        map = {}
        for w in sortedFeatures:
            map[w] = 0
        tweet_words = t[0]
        tweet_opinion = t[1]
        for word in tweet_words:
            if word in map:
                map[word] = 1
        values = map.values()
        feature_vector.append(values)
        if tweet_opinion == 'positive':
            label = 0
        elif tweet_opinion == 'negative':
            label = 1
        labels.append(label)
    return {'feature_vector': feature_vector, 'labels': labels}

**Comment by mluders** [comment]
I just updated the dataset. I included a .csv file, which contains the average twitter sentiment for every hour.
